config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/partnrs', to: 'pages#partnrs'
  get '/confirmation/:good_id', to: 'pages#confirmation', as: :confirmation
  get '/contract/:good_id', to: 'pages#contract', as: :contract
  resources :users, only: :show

  namespace :admin do
    resources :goods, except: %i[show index]
  end

  resources :partners, only: :destroy
  resources :goods, only: %i[show index] do
    resources :partners, only: %i[ create ]
  end
  root to: 'goods#index'

end

app/views/shared/_navbar.html.erb
<div class="partnr-container">
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#">
      <div class="partnr-logo">
        <%= link_to (user_signed_in? ? goods_path : :root) do %>
          <%= image_tag "partnr_light.png" %>
        <% end %>
      </div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item d-flex flex-column justify-content-center">
            <%= link_to "VEÍCULOS", goods_path, class: "btn btn-link mr-3" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item d-flex flex-column justify-content-center">
              <%= link_to (current_user.adm? ? 'DASHBOARD' : 'MEUS PARCEIROS'), partnrs_path, class: "btn btn-link mr-3 pr-3" %>
          </li>
          <% if current_user.adm? %>
            <li class="nav-item d-flex flex-column justify-content-center">
                <%= link_to "ADICIONAR VEÍCULO", new_admin_good_path, class: "btn btn-link mr-3 pr-3" %>
            </li>
          <% end %>
          <li class="nav-item d-flex flex-column justify-content-center">
              <%= link_to "SAIR", destroy_user_session_path, method: :delete, class: "btn btn-outline-partnr-yellow mr-3" %><span class="sr-only">(current)</span>
          </li>
          <li class="nav-item d-flex flex-column justify-content-center">
            <span class="navbar-text">
              <%= link_to user_path(current_user) do %>
                <%= cl_image_tag current_user.profile_picture, width:50, height: 50, crop: :thumb, gravity: :face %>
              <% end %>
            </span>
          </li>
        <% else %>
          <li class="nav-item d-flex flex-column justify-content-center">
              <%= link_to t(".sign_in", default: "ENTRAR"), new_user_session_path, class: "btn btn-link mr-3 pr-3" %>
          </li>
          <li class="nav-item d-flex flex-column justify-content-center">
              <%= link_to t(".sign_in", default: "CRIAR CONTA"), new_user_registration_path, class: "btn btn-outline-partnr-yellow mr-3" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_search.html.erb
<div class="w-100 p-5">

  <%= form_for goods_path, method: 'GET', remote: true do |f| %>

    <h5>Busca</h5>
    <%= text_field_tag :query,
      params[:query],
      class: 'form-control mb-3',
      placeholder: 'Procurar' %>

    <h5 class="mt-5">Filtros</h5>
    <%= select_tag :good_type,
      options_for_select(@good_types),
      class: 'form-control mb-3 good-type',
      prompt: "Encontre o seu próximo..." %>

    <%= select_tag :fabrication_year,
      options_for_select(@fabrication_year_range),
      class: 'form-control mb-3 good-fabrication-year',
      prompt: "Ano de fabricação" %>

    <%= select_tag :color,
      options_for_select(@colors),
      class: 'form-control mb-3 good-color',
      prompt: "Cor" %>

    <%= select_tag :body_style,
      options_for_select(@body_styles),
      class: 'form-control mb-5 good-body-style',
      prompt: "Tipo" %>

    <span class="text-uppercase text-partnr-dark-gray">Quilometragem</span><small> até</small>
    <div class="h4 text-partnr-dark-gray font-weight-light">
      <span id="mileage-range-output"></span>&nbspkm
    </div>
    <%= f.range_field :kilometers, min: @min_mileage, max: @max_mileage, step: (@max_mileage - @min_mileage) / 10, value: @max_mileage, class: "mb-4 custom-range mileage-range" %>

    <span class="mt-4 text-uppercase text-partnr-dark-gray">Preço</span><small> até</small>
    <div class="h4 text-partnr-dark-gray font-weight-light">
      R$&nbsp<span id="price-range-output"></span>
    </div>
    <%= f.range_field :price, min: @min_price, max: @max_price, step: (@max_price - @min_price) / 10, value: @max_price, class: "custom-range price-range" %>

    <%= submit_tag "", id: 'submit-search', style: "display: none;" %>

    <!-- gets range value and injects it into the right element -->
    <script>
      var mileageSlider = document.querySelector(".mileage-range");
      var mileageOutput = document.getElementById("mileage-range-output");
      var priceSlider = document.querySelector(".price-range");
      var priceOutput = document.getElementById("price-range-output");

      mileageOutput.innerHTML = mileageSlider.value;
      priceOutput.innerHTML = priceSlider.value; // Display the default slider value

      // update slider value w/ current value (each time you drag the slider handle)
      mileageSlider.oninput = function() {
        mileageOutput.innerHTML = this.value;
      }
      priceSlider.oninput = function() {
        priceOutput.innerHTML = this.value;
      }

      // add event listener (on click) for all search fields (except the text/query search field)
      attributes = [
        // slider (taking advantage on var 'slider' defined earlier)
        mileageSlider,
        priceSlider,
        document.querySelector(".good-type"),
        document.querySelector(".good-fabrication-year"),
        document.querySelector(".good-color"),
        document.querySelector(".good-body-style")
      ];
      for (var i = 0; i < attributes.length; i++) {
        attributes[i].addEventListener("click", (event) => {
          document.getElementById('submit-search').click();
        })
      }

    </script>

  <% end %>
</div>