config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/partnrs', to: 'pages#partnrs'
  get '/confirmation/:good_id', to: 'pages#confirmation', as: :confirmation
  get '/contract/:good_id', to: 'pages#contract', as: :contract
  resources :users, only: :show

  namespace :admin do
    resources :goods, except: %i[show index]
  end

  resources :partners, only: :destroy
  resources :goods, only: %i[show index] do
    resources :partners, only: %i[ create ]
  end
  root to: 'goods#index'

end

app/views/pages/confirmation.html.erb
<div class="container">
  <div class="row">
    <% @good.users.each do |user| %>
      <% unless user == current_user %>
        <div class="col-xs-12 col-lg-4">
          <div class="card confirmation-card">
            <div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_url "#{user.favorite}.jpg"%>)" class="profile-photo">
              <%= cl_image_tag user.profile_picture, width:100, height: 100, crop: :thumb, gravity: :face, class: 'profile-pic', style: "border-radius: 50%" %>
              <h5 class="confirmation-profile-name "><%= user.first_name %>  <%= user.last_name %></h5>
            </div>
            <div class="card-body profile-content">
              <br>
              <h5>Info</h5>
              <p><i class="far fa-id-card"> <%= user.CPF %></i></p>
              <p><i class="fas fa-briefcase"> <%= user.occupation %></i></p>
              <p><i class="fas fa-home"> <%= user.address %></i></p>
              <br>
              <div class="bg-white">
                <h5>Contact</h5>
                <p><i class="fas fa-at"> <%= user.email %></i></p>
                <p><i class="fas fa-phone"> <%= user.phone_number %></i></p>
              </div>
              <br>
              <h5>About me</h5>
              <p><i class="fas fa-book-open"> <%= user.bio %></i></p>

              <h4 class="border border-warning border-top-0 border-left-0 border-right-0 text-center"><%= user.first_name.capitalize %> afirmou que:</h4>

              <% if @good.good_type.capitalize == 'Carro' %>
                <% @good.partners.where(user: user) %>
                <p>Pretende guiar em média <strong><%= @good.partners.find_by(user: user).km_month.nil? ? '0' : @good.partners.find_by(user: user).km_month %></strong> kilometers por mês</p>
                <p>track use<%= @good.partners.find_by(user: user).track_use %></p>
                <p>other drivers<%= @good.partners.find_by(user: user).other_drivers %></p>
              <% elsif @good.good_type.capitalize == 'Barco' %>
                <p>Pretende levar em média <strong><%= @good.partners.find_by(user: user).numberber_of_passengers.nil? ? '0' : @good.partners.find_by(user: user).numberber_of_passengers %></strong> passageiros</p>
                <p>Pretende navegar em média <strong><%= @good.partners.find_by(user: user).km_month.nil? ? '0' : @good.partners.find_by(user: user).km_month %></strong> milhas por mês</p>
                <p>Pretende usar <strong><%= @good.partners.find_by(user: user).frenquency_month.nil? ? '0' : @good.partners.find_by(user: user).frenquency_month %></strong> vezes por mês</p>
                <p><strong><%= @good.partners.find_by(user: user).for_work.nil? ? 'Nao vai':'Vai' %></strong> ser usado para trabalho</p>
              <% elsif @good.good_type.capitalize == 'Helicoptero' %>
                <p><%= @good.partners.find_by(user: user).numberber_of_passengers %></p>
                <p>Pretende voar em média <strong><%= @good.partners.find_by(user: user).km_month.nil? ? '0' : @good.partners.find_by(user: user).km_month %></strong> milhas por mês</p>
                <p>Pretende usar <strong><%= @good.partners.find_by(user: user).frenquency_month.nil? ? '0' : @good.partners.find_by(user: user).frenquency_month %></strong> vezes por mês</p>
                <p><strong><%= @good.partners.find_by(user: user).for_work.nil? ? 'Nao vai':'Vai' %></strong> ser usado para trabalho</p>
              <% elsif @good.good_type.capitalize == 'Jatinho' %>
                <p>Pretende levar em média <strong><%= @good.partners.find_by(user: user).numberber_of_passengers.nil? ? '0' : @good.partners.find_by(user: user).numberber_of_passengers %></strong> passageiros</p>
                <p>Pretende voar em média <strong><%= @good.partners.find_by(user: user).km_month.nil? ? '0' : @good.partners.find_by(user: user).km_month %></strong> milhas por mês</p>
                <p>Pretende usar <strong><%= @good.partners.find_by(user: user).frenquency_month.nil? ? '0' : @good.partners.find_by(user: user).frenquency_month %></strong> vezes por mês</p>
                <p><strong><%= @good.partners.find_by(user: user).for_work.nil? ? 'Nao vai':'Vai' %></strong> ser usado para trabalho</p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="m-3 text-center">
    <%= link_to 'CONFIRM', contract_path(@good), data: {confirm: "Sim, estou de acordo com meus partnrs e quero comprar o #{@good.brand} #{@good.model}"}, class:'btn btn-partnr btn-partnr-blue px-4 py-3 mr-2' %>
    <%= link_to 'CANCEL', partner_path(@partner), method: 'delete', data: {confirm: "Sim, confirmo que quero cancelar a compra de meu #{@good.brand} #{@good.model} order"}, class:'btn btn-outline-partnr-dark-gray px-4 py-3 ml2' %>
  </div>
</div>

app/views/pages/contract.html.erb
<div class="d-flex partnr-container p-5">
  <!-- this div serves as  -->
  <% if @good.partners.pluck(:step).uniq == ['confirmed'] %>
    <div id='container' class="contract col-sm-12 col-md-8"></div>
  <% else %>
    <div id="fake-contract-container" class="contract col-sm-12 col-md-8 bg-white rounded p-5 text-center ">
      <h4 class="m-5"><div class="mx-5">Estamos aguardando seus partners confirmarem interesse para gerarmos seu contrato!</div></h4>
      <div class="text-center px-4 pt-2 display-4 text-partnr-yellow"><%= icon('far', 'clock') %></div>
    </div>
  <% end %>
  <div class="status-box col-sm-12 col-md-3 offset-md-1 bg-white p-5">
    <h3 class="mb-5">Status</h3>
    <div class="mb-4 mt-1">
      <% @good.users.each do |user| %>
        <% unless user == current_user %>
          <div class="mb-3"><%= cl_image_tag user.profile_picture, class: 'avatar' %>
            <% if user.partners.where(good: @good).first.step == "notified" %>
              <span class="ml-3 text-warning">Aguardando confirmacao</span>
            <% elsif user.partners.where(good: @good).first.step == "confirmed" %>
              <span class="ml-3 text-primary">Aguardando assinatura</span>
            <% else %>
              <span class="ml-3 text-success">Contrato assinado</span>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    // Carrega o widget embedded com a request_signature_key
    widget = new Clicksign("<%= @good.partners.where(user: current_user).first.request_signature_key %>");

    // Define o endpoint https://sandbox.clicksign.com ou https://app.clicksign.com
    widget.endpoint = 'https://app.clicksign.com';

    // Define a URL de origem (parametro necessário para utilizar através de WebView)
    widget.origin = 'https://partnr.live';
    // widget.origin = 'https://partnr.me';

    widget.mount('container');

  </script>
<% end %>

app/views/pages/home.html.erb
<div class="home-page">
  <div class="col-xs-12">
    <h1 class="about">Estilo de vida luxuoso compartilhado.</h1>
    <br>
    <h1 class="clickme">Quer saber mais sobre nossos veículos? Clique <%= link_to "aqui.", goods_path %></h1>
  </div>
</div>

app/views/pages/partnrs.html.erb
<div class="container partners-container">
  <% if current_user.partners.empty? %>
  <div class="no-partners">
    <h1>Sorry <%= current_user.first_name %> it seems like you don't have any PARTNERS yet</h1>
    <p>go to the index page and ...</p>
  </div>
  <% else %>
    <% @goods.each do |good| %>
      <%= link_to good_path(good), class: 'partners-center no-deco' do %>
        <div class="my-card" style="background-image: url(<%= asset_url "#{good.good_type}.jpg"%>); background-size: cover">
          <div class="good-title"><%= good.brand %> <%= good.model %></div>
          <div class="partners-show-flex">
            <% good.users.each do |user| %>
              <%= cl_image_tag user.profile_picture, height: 100, width: 100, crop: :thumb, gravity: :face, class: 'rounded-circle avatar', data:{ toggle: 'popover', trigger: 'hover', placement: 'top', content: "#{user.first_name}"} %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>